[project]
name = "start-mesh"
authors = ["Mesh Team <team@startmesh.io>"]
description = "Goal Achievement and Reward Platform"
telemetry = false
requirements = []
[contracts.mesh-goals]
path = "contracts/mesh-goals.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
